substitutions:
  name: athom-smart-plug-v3-50e864
  friendly_name: Dehumidifier
  max_humidity_default: '57.0'

packages:
  Athom_Technology.Smart_Plug_V3: !include modules/athom-smart-plug.yaml

# captive_portal: !remove
# web_server: !remove

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Local program
# Home Assistant sensor for humidity
sensor:
  - platform: homeassistant
    entity_id: sensor.basement_humidity
    id: basement_humidity
    internal: true

time:
  - platform: sntp
    id: !extend sntp_time
    update_interval: 360min   # Change sync interval from default 5min to 6 hours
    timezone: "America/New_York"    
    on_time_sync:
      then:
        - delay: 60s
        - if:   # Publish the time the device was last restarted, but only once.
            condition:
              lambda: 'return id(device_last_restart).state == "";'
            then:
              - text_sensor.template.publish:
                  id: device_last_restart
                  state: !lambda 'return id(sntp_time).now().strftime("%a %d %b %Y - %I:%M:%S %p");'
    on_time:
      - seconds: 0
        minutes: 0
        hours: 18,19,20,21,22,23,0,1,2,3,4,5,6,7,8
        then:
          - if: # Automation to control the switch based on humidity between 6pm and 8am
              condition:
                lambda: |-
                  return id(basement_humidity).state > 57;
              then:
                - switch.turn_on: relay
                - logger.log:
                    format: "Relay on"
              else:
                - switch.turn_off: relay
                - logger.log:
                    format: "Relay off"
      - seconds: 0
        minutes: 0
        hours: 9
        then:
          - switch.turn_off: relay # Turn off at 9AM
          - logger.log:
             format: "Relay off"
