packages:
  Athom_Technology.Smart_Plug_V3: !include modules/athom-smart-plug.yaml

esphome:
  name: athom-smart-plug-v3-50f144
  name_add_mac_suffix: false
  friendly_name: Fairy Light

api:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

sun:
  latitude: !secret latitude
  longitude: !secret longitude
  on_sunset:
    - elevation: -3.5°
      then:
        - switch.turn_on: # Turn on at sunset
            id: relay

time:
  - platform: sntp
    id: !extend sntp_time
    update_interval: 360min   # Change sync interval from default 5min to 6 hours
    timezone: "America/New_York"
    on_time_sync:
      then:
        - delay: 60s
        - logger.log: "Synchronized SNTP clock"
        - if:   # Publish the time the device was last restarted, but only once.
            condition:
              lambda: 'return id(device_last_restart).state == "";'
            then:
              - text_sensor.template.publish:
                  id: device_last_restart
                  state: !lambda 'return id(sntp_time).now().strftime("%a %d %b %Y - %I:%M:%S %p");'
    on_time:  # Turn off at midnight
      - seconds: 0
        minutes: 0
        hours: 0
        then:
          - switch.turn_off: relay
