substitutions:
  name: athom-smart-plug-v3-50ebc0
  friendly_name: Couch_Lamp

packages:
  Athom_Technology.Smart_Plug_V3: !include modules/athom-smart-plug.yaml

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

time:
  - platform: sntp
    id: !extend sntp_time
    update_interval: 360min   # Change sync interval from default 5min to 6 hours
    timezone: "America/New_York" 
    on_time_sync:
      then:
        - if:   # Publish the time the device was last restarted, but only once.
            condition:
              lambda: 'return id(device_last_restart).state == "";'
            then:
              - text_sensor.template.publish:
                  id: device_last_restart
                  state: !lambda 'return id(sntp_time).now().strftime("%a %d %b %Y - %I:%M:%S %p");'

