substitutions:
  name: "guition-esp32-s3-4848s040"
  friendly_name: "Guition480"
  device_description: "Guition ESP32-S3-4848S040 480*480 Smart Screen"

  lightbulb:         "\U000F0335"
  ceiling_light:     "\U000F0769"
  lamp:              "\U000F06B5"
  floor_lamp:        "\U000F08DD"
  string_lights:     "\U000F12BA"
  track_light:       "\U000F0914"
  bulkhead_light:    "\U000F1A2F"
  led_strip:         "\U000F07D6"
  coach_lamp:        "\U000F1020"
  ceiling_fan_light: "\U000F1798"

  icon_font: light40
  text_font: roboto24
  screen_height: '480px'
  screen_width: '480px'
  button_on_color: "burnt_sienna"
  button_off_color: "very_dark_gray"
  icon_on_color: "yellow"
  icon_off_color: "gray"
  label_on_color: "white"
  label_off_color: "gray"
  button_text_color: "white"
  button_height_single: '109px'
  button_height_double: '228px'
  button_width: '150px'
  touchscreen_idle_timeout: "120s"
  touchscreen_daytime_brightness: "100%"
  touchscreen_nighttime_brightness: "50%"
  # Screen goes to sleep at Mightnight
  screen_sleep_hour: '0'
  screen_sleep_minute: '0'
  # Screen wakes up at 5:30am
  screen_wake_hour: '5'
  screen_wake_minute: '30'

  button_1_name: "Local Light"
  button_1_id: local_light
  button_1_icon: $lightbulb
  button_1_device: "internal_relay_1"

  button_2_name: "Button 2"
  button_2_id: couch_lamp
  button_2_icon: $lightbulb
  button_2_device: "switch.athom_smart_plug_v3_50ebc0_switch"

  # Button 3 is an empty object that requires no settings. It just pushes everything down one button

  button_4_name: "RGB light"
  button_4_id: rgb_light
  button_4_icon: $string_lights
  button_4_device: light.athom_rgb_light_d93662_rgb_light_strip

globals:
# Keeps track of late night mode for turning off the backlight
  - id: late_night_mode
    type: bool
    restore_value: false
    initial_value: 'false'
    
packages:
  base: !include modules/common_base.yaml
  webserver: !include modules/wifi_base.yaml
  hardware: !include modules/hardware/guition-esp32-s3-4848s040.yaml
  colors: !include modules/common/color.yaml
  fonts: !include modules/common/fonts.yaml  
  time: !include modules/lvgl/lvgl_time_sntp.yaml
  sensors: !include modules/lvgl/lvgl_sensors_base.yaml

esphome:
  on_boot:
    priority: -100
    then:
      - delay: 60s
      - lvgl.widget.hide: boot_screen

# -------------------------------------------------------------------------
# Button state - Update state for Homeassistant objects and internal relays
# -------------------------------------------------------------------------

# Internal Relays defined as lights go here
light:
  - !include { file: modules/lvgl/basic_local_relay_button_state.yaml, vars: { id: 1 } }

# Update button state from Home Assistant
text_sensor:
  - !include { file: modules/lvgl/basic_switch_button_state.yaml, vars: { id: 2 } }
  - !include { file: modules/lvgl/basic_switch_button_state.yaml, vars: { id: 4 } }

sensor:
  - !include { file: modules/lvgl/dimmer_light_state.yaml, vars: { id: 4 } }

#-------------------------------------------
# LVGL pages and Buttons
#-------------------------------------------

# Wake screen on touch
touchscreen:
  on_touch:
    then:
      - logger.log: "LVGL is active"
      - lvgl.resume:
      - if:
      # Only turn on baclight and set to 50% if late_night_mode is on
          condition:
            - lambda: |-
                return id(late_night_mode);
          then:
            - light.turn_on:
                id: display_backlight
                brightness: 50%

# Main LVGL section
lvgl:
  displays:
    - my_display
  touchscreens:
    - my_touchscreen
  on_idle: !include { file: modules/lvgl/lvgl_touchscreen_idle.yaml }

  theme: !include { file: modules/lvgl/lvgl_theme.yaml }
  page_wrap: true

# Boot Screen
  top_layer: !include { file: modules/lvgl/boot_screen.yaml, vars: { height: $screen_height, width: $screen_width  } }

# Main Page
  pages:
    - id: main_page
      layout:
        type: flex
        flex_flow: COLUMN_WRAP
      width: 100%
      bg_color: black
      bg_opa: cover
      pad_all: 5
      widgets: # Include all the buttons
        - button: !include { file: modules/lvgl/basic_local_relay_button.yaml, vars: { id: 1, height: $button_height_double } }
        - button: !include { file: modules/lvgl/basic_switch_button.yaml, vars: { id: 2, height: $button_height_single } }
        - button: !include { file: modules/lvgl/transparent_empty_button.yaml, vars: { id: 3, height: $button_height_single } }
        - button: !include { file: modules/lvgl/dimmer_light_button.yaml, vars: { id: 4, height: $button_height_double } }

#-------------------------------------------
# Graphics and Fonts
#-------------------------------------------
image:
  - file: https://esphome.io/_static/logo-text-on-light.svg
    id: boot_logo
    resize: 460x90
    type: RGB565
    use_transparency: true


