substitutions:
  name: "sdl-lvgl"
  friendly_name: "SDL test system"

  lightbulb:         "\U000F0335"
  ceiling_light:     "\U000F0769"
  lamp:              "\U000F06B5"
  floor_lamp:        "\U000F08DD"
  string_lights:     "\U000F12BA"
  track_light:       "\U000F0914"
  bulkhead_light:    "\U000F1A2F"
  led_strip:         "\U000F07D6"
  coach_lamp:        "\U000F1020"
  ceiling_fan_light: "\U000F1798"

  icon_font: light24
  text_font: roboto18
  screen_height: "480px"
  screen_width: "800px"
  sdl_height: "480"
  sdl_width: "800"  
  button_on_color: "burnt_sienna"
  button_off_color: "Very_Dark_Gray"
  icon_on_color: "yellow"
  icon_off_color: "gray"
  label_on_color: "white"
  label_off_color: "gray"
  button_text_color: "white"
  button_height_single: '85px'
  button_height_double: '181px'
  button_width: '150px'
  touchscreen_idle_timeout: "120s"
  touchscreen_daytime_brightness: "100%"
  touchscreen_nighttime_brightness: "50%"
  # Screen goes to sleep at Mightnight
  screen_sleep_hour: '0'
  screen_sleep_minute: '0'
  # Screen wakes up at 5:30am
  screen_wake_hour: '5'
  screen_wake_minute: '30'

  button_1_name: "Couch Lamp"
  button_1_id: couch_lamp
  button_1_icon: $lightbulb
  button_1_device: "switch.athom_smart_plug_v3_50ebc0_switch"

  button_2_name: "Button 2"
  button_2_id: button_2
  button_2_icon: $floor_lamp
  button_2_device: "switch.athom_smart_plug_v3_50ebc0_switch"

  button_3_name: "Button 3"
  button_3_id: button_3
  button_3_icon: $floor_lamp
  button_3_device: "switch.athom_smart_plug_v3_50ebc0_switch"

  button_4_name: "Button 4"
  button_4_id: button_4
  button_4_icon: $floor_lamp
  button_4_device: "switch.athom_smart_plug_v3_50ebc0_switch"

  button_5_name: "Button 5"
  button_5_id: button_5
  button_5_icon: $floor_lamp
  button_5_device: "switch.athom_smart_plug_v3_50ebc0_switch"

  button_6_name: "Button 6"
  button_6_id: button_6
  button_6_icon: $floor_lamp
  button_6_device: "switch.athom_smart_plug_v3_50ebc0_switch"

  button_7_name: "Button 7"
  button_7_id: button_7
  button_7_icon: $floor_lamp
  button_7_device: "switch.athom_smart_plug_v3_50ebc0_switch"

  button_8_name: "Button 8"
  button_8_id: button_8
  button_8_icon: $floor_lamp
  button_8_device: "switch.athom_smart_plug_v3_50ebc0_switch"

  button_9_name: "Button 9"
  button_9_id: button_9
  button_9_icon: $floor_lamp
  button_9_device: "switch.athom_smart_plug_v3_50ebc0_switch"


globals:
  - id: late_night_mode
    type: bool
    restore_value: false
    initial_value: 'false'

# We need this until 2024.11.0
external_components:
  - source: github://pr#7631
    components: [ image, lvgl ]  

packages:
  base: !include modules/common_base.yaml
#  webserver: !include modules/wifi_base.yaml
#  hardware: !include modules/hardware/guition-esp32-s3-4848s040.yaml
  hardware: !include modules/hardware/SDL-lvgl.yaml
  colors: !include modules/common/color.yaml
  time: !include modules/lvgl/lvgl_time_homeassistant.yaml
  sensors: !include modules/lvgl/lvgl_sensors_base-SDL.yaml

esphome:
  on_boot:
    priority: -100
    then:
      - delay: 60s
      - lvgl.widget.hide: boot_screen

# -------------------------------------------------------------------------
# Button state - Update state for Homeassistant objects and internal relays
# -------------------------------------------------------------------------

# Homeassistant lights go here
text_sensor:
  - !include { file: modules/lvgl/basic_switch_button_state.yaml, vars: { id: 1 } }
  - !include { file: modules/lvgl/basic_switch_button_state.yaml, vars: { id: 2 } }

#-------------------------------------------
# LVGL pages and Buttons
#-------------------------------------------

# Wake screen on touch
touchscreen:
  on_touch:
    then:
      - logger.log: "LVGL is active"
      - lvgl.resume:
      - if:
      # Only turn on baclight and set to 50% if late_night_mode is on
          condition:
            - lambda: |-
                return id(late_night_mode);
          then:
            - light.turn_on:
                id: display_backlight
                brightness: 50%

# Main LVGL section
lvgl:
  displays:
    - my_display
  touchscreens:
    - my_touchscreen
  on_idle: !include { file: modules/lvgl/lvgl_touchscreen_idle.yaml }

  theme: !include { file: modules/lvgl/lvgl_theme.yaml }
  page_wrap: true

# Boot Screen
  top_layer: !include { file: modules/lvgl/boot_screen.yaml }

# Main Page
  pages:
    - id: main_page
      layout:
        type: flex
        flex_flow: column_wrap
      width: 100%
      bg_color: Black
      bg_opa: cover
      pad_all: 5
      widgets:
        - button: !include { file: modules/lvgl/basic_switch_button.yaml, vars: { id: 1, height: $button_height_double } }
        - button: !include { file: modules/lvgl/basic_switch_button.yaml, vars: { id: 2, height: $button_height_single } }
        - button: !include { file: modules/lvgl/basic_switch_button.yaml, vars: { id: 3, height: $button_height_single } }
        - button: !include { file: modules/lvgl/basic_switch_button.yaml, vars: { id: 4, height: $button_height_single } }
        - button: !include { file: modules/lvgl/basic_switch_button.yaml, vars: { id: 5, height: $button_height_single } }
        - button: !include { file: modules/lvgl/basic_switch_button.yaml, vars: { id: 6, height: $button_height_single } }
        - button: !include { file: modules/lvgl/basic_switch_button.yaml, vars: { id: 7, height: $button_height_single } }
        - button: !include { file: modules/lvgl/basic_switch_button.yaml, vars: { id: 8, height: $button_height_single } }
        - button: !include { file: modules/lvgl/basic_switch_button.yaml, vars: { id: 9, height: $button_height_single } }


#-------------------------------------------
# Graphics and Fonts
#-------------------------------------------
image:
  - file: https://esphome.io/_static/logo-text-on-light.svg
    id: boot_logo
    resize: 460x90
    type: RGB565
    use_transparency: true

font:
  - file: "gfonts://Roboto"
    id: roboto18
    size: 18
    bpp: 8
    extras:
      # http://materialdesignicons.com/cdn/7.4.47/
      - file: 'https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf'
        glyphs: [
          "\U000F004B",
          "\U0000f0ed",
          "\U000F006E",
          "\U000F012C",
          "\U000F179B",
          "\U000F0748",
          "\U000F1A1B",
          "\U000F02DC",
          "\U000F0A02",
          "\U000F035F",
          "\U000F0156",
          "\U000F0C5F",
          "\U000f0084",
          "\U000f0091",
        ]

  # http://materialdesignicons.com/cdn/7.4.47/
  - file: 'https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf'
    id: light24
    size: 24
    bpp: 8
    glyphs: [
      "\U000F0335",  # mdi-lightbulb
      "\U000F0769",  # mdi-ceiling-light
      "\U000F06B5",  # mdi-lamp
      "\U000F08DD",  # mdi-floor-lamp
      "\U000F12BA",  # mdi-string-lights
    ]
