---
# Dimmer light button state - define its settings in substitutions
sensor:
  - platform: homeassistant
    id: button_${id}_device_brightness
    entity_id: $button_${id}_device
    attribute: brightness
    on_value:
      - lvgl.slider.update:
          id: lv_button_${id}_slider
          value: !lambda return x;

<<: !include ./basic_switch_or_light_button_state.yaml