# lilygo tdisplays3 170px * 320px Smart Screen
# Hardware configuration file

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  min_version: 2024.11.0
  platformio_options:
    board_build.f_flash: 80000000L
    board_build.partitions: default_16MB.csv
    board_build.arduino.memory_type: qio_opi

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: arduino
  flash_size: 16MB
  
external_components:
  - source: github://landonr/lilygo-tdisplays3-esphome
    components: [tdisplays3]  

preferences:
  flash_write_interval: 1min

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO0
      inverted: true
    name: "Button 1"
  - platform: gpio
    pin: 
      number: GPIO14
      inverted: true
    name: "Button 2"

output:
  - platform: ledc
    pin: GPIO38
    id: GPIO38
    frequency: 2000

light:
  - platform: monochromatic
    output: GPIO38
    name: Display Backlight
    id: display_backlight
    restore_mode: ALWAYS_ON

# 320x170 LCD screen
display:
  - platform: tdisplays3
    id: my_display
    update_interval: never
    auto_clear_enabled: False

#touchscreen: 
# None